config/routes.rb
Rails.application.routes.draw do

  # Navigation routes
  get 'home', to: "home#index"
  get 'login', to: "login#index"
  get 'login/signup', to: "login#signup"
  get 'login/forgotpassword', to: "login#forgotpassword"
  get 'characters', to: "characters#index"
  get 'char_classes', to: "char_classes#index"
  get 'char_heritages', to: "char_heritages#index"
  get 'equips', to: "equips#index"
  get 'spells', to: "spells#index"

  # Logging and authentication routes
  post 'login', to: "sessions#create"
  post 'login/signup', to: "users#create"
  get 'me', to: "users#self"
  delete 'login/logout', to: "sessions#destroy"

  resources :personal_spells
  resources :personal_equips
  resources :levels
  resources :playe_heritages
  resources :player_classes
  resources :turnings
  resources :spell_per_levels
  resources :hit_dices
  resources :experience_levels
  resources :attack_bonus
  resources :saves
  resources :equipment
  resources :armors
  resources :spells
  resources :weapons
  resources :characters
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "home#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/char_class.rb
class CharClass < ApplicationRecord
  has_many :levels
  has_many :spells
  has_many :characters
end

app/models/char_heritage.rb
class CharHeritage < ApplicationRecord
  has_many :characters
end

app/models/character.rb
class Character < ApplicationRecord
  belongs_to :user
  belongs_to :char_class
  belongs_to :char_heritage
  has_many :personal_equips
  has_many :personal_spells
end

app/models/equip.rb
class Equip < ApplicationRecord
  has_many :personal_equips
end

app/models/level.rb
class Level < ApplicationRecord
  belongs_to :char_class
end

app/models/personal_equip.rb
class PersonalEquip < ApplicationRecord
  belongs_to :character
  belongs_to :equip
end

app/models/personal_spell.rb
class PersonalSpell < ApplicationRecord
  belongs_to :character
  belongs_to :spell
end

app/models/spell.rb
class Spell < ApplicationRecord
  belongs_to :class
end

app/models/user.rb
class User < ApplicationRecord
  
  has_secure_password
  
  has_many :characters

  validates :username, uniqueness: true
  validates :username, length: { minimum: 5 }, allow_blank: true
  validates :email, presence: true
  validates :password, length: { minimum: 8 }, allow_blank: true

  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

end

app/controllers/equips_controller.rb
class EquipsController < ApplicationController

  before_action :authorize
  skip_before_action :authorize, only: [:index]

  def index
  end

  private

  def equip_params
    params.require(:equip).permit(:name, :weapon, :damage, :attack_modifier, :special, :range, :blunt, :brace, :charge, :melee, :missile, :reload, :slow, :splash_weapon, :two_handed, :armor, :armor_class, :cost, :weight, :special)
  end

  def authorize
    return render json: { error: "Not authorized" }, status: :unauthorized unless session.include? :user_id
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/login_controller.rb
class LoginController < ApplicationController

  def index
  end

  def is_logged_in?
    false
  end
  helper_method :is_logged_in?

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :authorize
  skip_before_action :authorize, only: [:create]

  def create
    if params[:password] == params[:password_confirmation]
      user = User.create(username: params[:username], password: params[:password], email: params[:email])
      if user.valid?
        session[:user_id] = user.id
        render json: user, status: :created
        flash[:success] = "You're logged in as #{user.username}"
        redirect_to 'home'
      else
        render json: { errors: user.errors.full_messages }, status: :unprocessable_entity
      end
    else
      render json: { errors: "Passwords do not match" }, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(user).permit(:username, :password, :email)
  end

  def authorize
    return render json: { error: "Not authorized" }, status: :unauthorized unless session.include? :user_id
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/equip_helper.rb
module EquipHelper
end

app/helpers/levels_helper.rb
module LevelsHelper
end

app/helpers/login_helper.rb
module LoginHelper

  def is_logged_in
    false
  end

end

app/helpers/signup_helper.rb
module SignupHelper
end

app/helpers/spells_helper.rb
module SpellsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/login/_login_card.html.erb
<div class="card lg:card-side bg-zinc-200 shadow-xl ml-6">
  <figure class="h-80"><img
    src='/img/tramp_minotaur.jpg'
    alt='Mighty minotaur'
    class='h-80'
  /></figure>
  <div class="card-body h-80">
    <%= turbo_frame_tag "login" do %>
      <%= form_with do |form| %>
        <div>
          <%= form.text_field :username, placeholder: "username", class: "w-full max-w-xs" %>
        </div>
        <div class="mt-2">
          <%= form.password_field :password, placeholder: "password",class: "w-full max-w-xs" %>
        </div>
        <div class="mt-2">
          <%= form.submit "LOGIN", class: "btn" %>
        </div>
      <% end %>
      <div class="block mt-2">
        <%= link_to "Create Account", login_signup_url %>
      </div>
      <div class="block mt-2">
        <%= link_to "Recover Password", login_forgotpassword_url %>
      </div>      
    <% end %>
  </div>
</div>

app/views/login/_logout_card.html.erb
<div class="card lg:card-side bg-zinc-200 shadow-xl ml-6">
  <figure class="h-80"><img
    src="/img/tramp_minotaur.jpg"
    alt="Mighty minotaur"
    class="h-80"
  /></figure>
  <div class="card-body h-80">
    <div class="card-actions">
      <%= button_to "Logout", {:controller => :sessions, :action => 'destroy' }, :method => :delete, class: "btn" %>
    </div>
  </div>
</div>

app/views/login/forgotpassword.html.erb
<%= turbo_frame_tag "login" do %>
  <%= form_with do |form| %>
    <div>
      <%= form.text_field :email, placeholder: "account email", class: "w-full max-w-xs" %>
    </div>
    <%= form.submit "Send recovery email", class: "btn mt-2" %>
  <% end %>
  <div class="mt-2">
    <%= link_to "Back to Login", login_url %>
  </div>
<% end %>

app/views/login/index.html.erb
<%= turbo_frame_tag "content" do %>
  <% if is_logged_in %>
    <% render "logout_card" %>
  <% else %>
    <% render "login_card" %>
  <% end %>
<% end %>

app/views/login/signup.html.erb
<%= turbo_frame_tag "login" do %>
  <%= form_with do |form| %>
    <div>
      <%= form.text_field :username, placeholder: "username", class: "w-full max-w-xs"  %>
    </div>
    <div class="mt-2">
      <%= form.password_field :password, placeholder: "password",  class: "w-full max-w-xs"  %>
    </div>
    <div class="mt-2">
      <%= form.password_field :password_confirmation, placeholder: "confirm password",  class: "w-full max-w-xs"  %>
    </div>
    <div class="mt-2">
      <%= form.email_field :email, placeholder: "email",  class: "w-full max-w-xs"  %>
    </div>
    <div class="mt-2">
      <%= form.submit "SUBMIT", class: "btn" %>
    </div>
  <% end %>
  <div class="mt-2">
    <%= link_to "Back to Login", login_url %>
  </div>
<% end %>